apiVersion: v1
kind: Service

metadata:
  name: taskflow-api-service

  labels:
    app: taskflow-api

spec:
  type: ClusterIP

  selector:
    app: taskflow-api

  ports:
    - name: http
      port: 80
      targetPort: 3000